tap "caskroom/cask"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/versions"
tap "neovim/neovim"
tap "thoughtbot/formulae"
tap "universal-ctags/universal-ctags"
brew "universal-ctags", args: ["HEAD"]
brew "apr"
brew "openssl"
brew "apr-util"
brew "augeas"
brew "autoconf"
brew "chromedriver", restart_service: true
brew "dialog"
brew "elasticsearch", restart_service: true
brew "gdbm"
brew "perl"
brew "git"
brew "gmp"
brew "hub"
brew "libtool"
brew "imagemagick"
brew "libevent"
brew "libffi"
brew "libssh"
brew "libxml2"
brew "libyaml"
brew "neovim"
brew "openssl@1.1"
brew "passenger"
brew "phantomjs"
brew "pkg-config"
brew "sqlite"
brew "postgresql", restart_service: true
brew "qt@5.5"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "siege"
brew "ssh-copy-id"
brew "the_silver_searcher"
brew "tree"
brew "vim"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
brew "thoughtbot/formulae/gitsh"
brew "thoughtbot/formulae/parity"
brew "thoughtbot/formulae/rcm"
brew "coreutils"
cask "gpgtools"
cask "dockertoolbox"
cask "virtualbox"
